### ISSUE TITLE
Missing Passenger Mount (Ground)

### ISSUE THREAD

**Issue by andi-74** [RavenousAddons/ravMounts#28]
## Actual behaviour
Explorer's Dunetrekker (1288) is not included when marked as favorite. This mount id is missing from data.lua

## Steps to reproduce this behaviour
• Mark Explorer's Dunetrekker as favorite
• Use /ravmounts passenger
• Adding this id to data.lua appears to fix the issue

@waldenp0nd

**Comment by waldenp0nd** [comment]
Thanks for the detailed report, I really appreciate it! I've pushed this up with the latest release (2.4.6).

https://github.com/RavenousAddons/ravMounts/releases/tag/2.4.6
