### ISSUE TITLE
Option locale not match

### ISSUE THREAD

**Issue by EKE00372** [RavenousAddons/ravMounts#31]
![image](https://github.com/RavenousAddons/ravMounts/assets/1412472/f78bfea6-9458-4bd8-9896-7c9593865204)

In cloneable option list, `focus` mean focus unitframe, but it actually use a globlastring mean hunter's power which also named focus, may cause wrong translate issue in other language.

Also, `STATUS_TEXT_BOTH` is normally show as "both" in most language client, but in zhCN it show "同時顯示", it means "show them in same time", not "both" so will make zhCN user confused probably.

suggest use `MINIMAP_TRACKING_FOCUS` for focus, use L.Both derectly.

**Comment by waldenp0nd** [comment]
Hey @EKE00372,

Thanks as well for this detailed report. I think I've fixed the misused globalstrings in the latest version, [2.8.20](https://github.com/RavenousAddons/ravMounts/releases/tag/v2.8.20).

I hope this solves things!

**Comment by EKE00372** [comment]
I've check zhTW/zhCN, It looks fine now.
